In [1]:
import pandas as pd

In [6]:
import pandas as pd

df = pd.read_csv("/content/netflix_titles.csv", encoding='latin1')
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [7]:
df.shape

(8809, 12)

In [8]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8809 entries, 0 to 8808
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8809 non-null   object
 1   type          8809 non-null   object
 2   title         8809 non-null   object
 3   director      6175 non-null   object
 4   cast          7984 non-null   object
 5   country       7978 non-null   object
 6   date_added    8799 non-null   object
 7   release_year  8809 non-null   int64
 8   rating        8805 non-null   object
 9   duration      8806 non-null   object
 10  listed_in     8809 non-null   object
 11  description   8809 non-null   object
dtypes: int64(1), object(11)
memory usage: 826.0+ KB

In [10]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.describe()

       release_year
count   8809.000000
mean    2014.181292
std        8.818932
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2024.000000

fill and fix null values

In [65]:
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')
df['year_added'] = df['date_added'].dt.year
df['month_added'] = df['date_added'].dt.month

In [66]:
df['country'] = df['country'].str.split(',').str[0]

In [68]:
df['country'] = df['country'].str.split(',').str[0]

In [70]:
df['duration_int'] = df['duration'].str.extract(r'(\d+)').astype(float)

In [77]:
df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Not Available')
df['country'] = df['country'].fillna('Unknown')
df['rating'] = df['rating'].fillna('Not rated')

df['duration_int'] = df['duration_int'].fillna(df['duration_int'].median())

In [78]:
def categorize(row):
    if row['type'] == 'TV Show':
        return 'TV Show'
    elif row['duration_int'] < 60:
        return 'Short'
    elif row['duration_int'] < 120:
        return 'Medium'
    else:
        return 'Long'

df['content_length_category'] = df.apply(categorize, axis=1)

In [79]:
df['primary_genre'] = df['listed_in'].str.split(',').str[0]

In [90]:
df_original = pd.read_csv("/content/netflix_titles.csv", encoding='latin1')

In [95]:
df['release_year'] = df_original['release_year']

In [96]:
df[['release_year']].head()

   release_year
0          2020
1          2021
2          2021
3          2021
4          2021

In [97]:
print(df.shape)
print(df.isnull().sum())
df.info()

(8711, 17)
show_id                    0
type                       0
title                      0
director                   0
cast                       0
country                    0
date_added                 0
release_year               0
rating                     0
duration                   0
listed_in                  0
description                0
duration_int               0
content_length_category    0
primary_genre              0
year_added                 0
month_added                0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
Index: 8711 entries, 0 to 8808
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   show_id                  8711 non-null   object
 1   type                     8711 non-null   object
 2   title                    8711 non-null   object
 3   director                 8711 non-null   object
 4   cast                     8711 non-null   object
 5   country                  8711 non-null   object
 6   date_added               8711 non-null   datetime64[ns]
 7   release_year             8711 non-null   int64
 8   rating                   8711 non-null   object
 9   duration                 8711 non-null   object
 10  listed_in                8711 non-null   object
 11  description              8711 non-null   object
 12  duration_int             8711 non-null   float64
 13  content_length_category  8711 non-null   object
 14  primary_genre            8711 non-null   object
 15  year_added               8711 non-null   int32
 16  month_added              8711 non-null   int32
dtypes: datetime64[ns](1), float64(1), int32(2), int64(1), object(12)
memory usage: 1.1+ MB

In [98]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,duration_int,content_length_category,primary_genre,year_added,month_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Not Available,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",90.0,Medium,Documentaries,2021,9
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2.0,TV Show,International TV Shows,2021,9
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,1.0,TV Show,Crime TV Shows,2021,9
3,s4,TV Show,Jailbirds New Orleans,Unknown,Not Available,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",1.0,TV Show,Docuseries,2021,9
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2.0,TV Show,International TV Shows,2021,9